[workspace]
members = [
    "src/stage_1st",
    "src/stage_2nd",
    "src/stage_3rd",
    "src/stage_4th",
    "src/plankton",
]
exclude = [
    "resources/eg-kernel",
    "resources/eg-kernel64"
]

[profile.release]
opt-level = "z"
