[workspace]
members = [
    "src/stage_1st",
    "src/stage_2nd",
    "src/stage_3r1",
    "src/stage_3r2",
    "src/plankton",
]
exclude = [
    "eg-kernel",
    "eg-kernel64"
]

[profile.release]
opt-level = "z"